basePath: /
definitions:
  handler.ResponseData:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      msg: {}
    type: object
host: localhost:8080
info:
  contact: {}
  description: 基于gin的个人博客项目
  title: blog项目接口文档
  version: "0.1"
paths:
  /user/register:
    post:
      consumes:
      - application/json
      description: 实现用户登录
      parameters:
      - in: query
        name: password
        type: string
      - in: query
        name: re_password
        type: string
      - in: query
        name: user_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ResponseData'
      summary: 用户登录接口
      tags:
      - user
swagger: "2.0"
